### ISSUE TITLE
Antivirus role needs to be ported from Gas Station

### ISSUE THREAD

**Issue by ProfessorManhattan** [megabyte-labs/install.doctor#15]
### 💡 Feature/Idea

The installation logic is already ported over and I began configuring `clamav` (details in the other ticket). Is the current logic enough to port the Gas Station logic over? It starts the service on all three Linux platforms:

```
  clamav:
    _bin: clamav-config
    _desc: '[ClamAV](https://www.clamav.net/) is an open-source antivirus engine for detecting trojans, viruses, malware & other malicious threats.'
    _docs: https://docs.clamav.net/
    _github: https://github.com/Cisco-Talos/clamav
    _home: https://www.clamav.net/
    _name: ClamAV
    _post: freshclam
    _service:apt: clamav-freshclam
    _service:dnf: clamd-freshclam
    _service:pacman: clamav-freshclam
    _type: cli
    apt:
      - clamav
      - clamdscan
    brew: clamav
    dnf:
      - clamav
      - clamav-update
    pacman: clamav
```

However, I'm not sure how we can add the cron on macOS. The cron updater for freshclam should be added to macOS as well, if possible.

Then, for `rkhunter`, the configuration is:

```
  rkhunter:
    _bin: rkhunter
    _desc: rkhunter is a Unix-based tool that scans for rootkits, backdoors and possible local exploits
    _docs: null
    _github: null
    _home: https://rkhunter.sourceforge.net/
    _name: rkhunter
    _post: rkhunter --propupd && rkhunter --update
    _service:pacman: cronie
    _type: cli
    apt: rkhunter
    brew: rkhunter
    dnf: rkhunter
    pacman:
      - cronie
      - rkhunter
      - s-nail
```

I'm not exactly sure how it works. What is `cronie` is being enabled for? How does it know to work with `rkhunter` to automatically get updated?

Anyway, the configurations should be stored in `home/dot_config/rkhunter/*` and then they can be applied in the `_post` install hook in `software.yml` or be seperated out into another script (might make more sense unless there is very little post install code).

Finally, both clamav and rkhunter should run on crons daily at 4AM and send email reports if they find anything. The email address can be found in the `home/.chezmoi.yaml.tmpl` and is available through template bindings with `{{ .user.email }}`.

Perhaps it will make most sense to send the emails to the user account (or wherever they normally go) and then configure that account to forward the emails out to the internet email address. I think you might be able to do this with a `~/.forward` file containing the email in the root user's home directory.

Configure outgoing SMTP to use a dummy GMail account that we can set in `.chezmoi.yaml.tmpl`.
